CREATE TABLE Banks_Hospitals (
	ID INT AUTO_INCREMENT NOT NULL UNIQUE,
	Name VARCHAR(50) NOT NULL UNIQUE,
	Street_Num INT NOT NULL,
	Street_Name VARCHAR(50) NOT NULL,
	City VARCHAR(30) NOT NULL,
	State CHAR(2) NOT NULL,
	Zip_Code INT NOT NULL,
	Facility_Type VARCHAR(3) NOT NULL,
	PRIMARY KEY(ID,Name)
);

CREATE TABLE Blood_Inventory (
	Name VARCHAR(50) NOT NULL UNIQUE,
	Opos INT NOT NULL,
	Oneg INT NOT NULL,
	Apos INT NOT NULL,
	Aneg INT NOT NULL,
	Bpos INT NOT NULL,
	Bneg INT NOT NULL,
	ABpos INT NOT NULL,
	ABneg INT NOT NULL,
	PRIMARY KEY(Name),
	FOREIGN KEY(Name) REFERENCES Banks_Hospitals(Name)
);

CREATE TABLE Blood_Platelets (
	Name VARCHAR(50) NOT NULL UNIQUE,
	Opos INT NOT NULL,
	Oneg INT NOT NULL,
	Apos INT NOT NULL,
	Aneg INT NOT NULL,
	Bpos INT NOT NULL,
	Bneg INT NOT NULL,
	ABpos INT NOT NULL,
	ABneg INT NOT NULL,
	PRIMARY KEY(Name),
	FOREIGN KEY(Name) REFERENCES Banks_Hospitals(Name)
);

CREATE TABLE Blood_Plasma (
	Name VARCHAR(50) NOT NULL UNIQUE,
	Opos INT NOT NULL,
	Oneg INT NOT NULL,
	Apos INT NOT NULL,
	Aneg INT NOT NULL,
	Bpos INT NOT NULL,
	Bneg INT NOT NULL,
	ABpos INT NOT NULL,
	ABneg INT NOT NULL,
	PRIMARY KEY(Name),
	FOREIGN KEY(Name) REFERENCES Banks_Hospitals(Name)
);

CREATE TABLE Login_Info (
	Username VARCHAR(30) NOT NULL UNIQUE,
	Pass VARCHAR(30) NOT NULL UNIQUE,
	Facility_Name VARCHAR(50),
	PRIMARY KEY(Username),
	FOREIGN KEY(Facility_Name) REFERENCES Banks_Hospitals(Name)
);
